import { Folder } from "@/types";

export const FooterMessages = [
  {
    name: "Folder",
    message: "Creates a new folder.",
  },
  {
    name: "Shortcut",
    message: "Creates a shortcut to quickly access your files or applications.",
  },
  {
    name: "TextDocument",
    message: "Creates a new text document for your notes and simple writings.",
  },
  {
    name: "CreateShortcut",
    message: "Creates shortcuts to the selected items.",
  },
  {
    name: "Delete",
    message: "Deletes the selected item.",
  },
  {
    name: "Rename",
    message: "Renames the selected item.",
  },
  {
    name: "Properties",
    message: "Displays the properties of the selected items.",
  },
  {
    name: "RefreshF5",
    message: "Refreshes the contents of current page.",
  },
  {
    name: "AboutOpceanAI",
    message: "Opens the OpceanAI about document.",
  },
];

export const folders: Folder[] = [
  {
    id: 1,
    name: "Recycle Bin",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/recycle-bin.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 2,
    name: "My Computer",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/computer-explorer.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 3,
    name: "Yuuki Models",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 4,
    name: "Doki Engine",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 5,
    name: "Okuru Runtime",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 6,
    name: "Flux Framework",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 7,
    name: "NHE Benchmark",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/folder.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 8,
    name: "About OpceanAI",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/help-book.png",
    isDocument: true,
    documentType: "markdown",
    documentPath: "/OpceanAI/About",
  },
  {
    id: 9,
    name: "Contact Us",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/modem.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
  {
    id: 10,
    name: "Control Panel",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/control-panel.png",
    isDocument: false,
    documentType: null,
    documentPath: null,
  },
];

export const programs = [
  {
    id: 11,
    name: "Internet Explorer",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/internet-explorer.png",
  },
  {
    id: 12,
    name: "Notepad",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/notepad.png",
  },
  {
    id: 13,
    name: "Calculator",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/calculator.png",
  },
  {
    id: 14,
    name: "MS-DOS Prompt",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/console-prompt.png",
  },
  {
    id: 15,
    name: "Display",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/display.png",
    description: "Adjust display settings such as resolution and color depth.",
  },
  {
    id: 16,
    name: "System",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/system.png",
    description: "View and manage system information and hardware settings.",
  },
  {
    id: 17,
    name: "Winamp",
    isOpen: false,
    isMaximized: false,
    isMinimized: false,
    image: "/icons/winamp.png",
    description:
      "A classic media player for playing your favorite music (using Youtube).",
  },
];

export const folderNavigationMenuItems = {
  file: [
    {
      label: "New",
      items: [
        { label: "Folder", disabled: true },
        { label: "Shortcut", disabled: true },
        { label: "Text Document", disabled: true },
      ],
    },
    { label: "Create Shortcut", disabled: true },
    { label: "Delete" },
    { label: "Rename" },
    { label: "Properties", disabled: true },
    { label: "Close" },
  ],
  edit: [
    { label: "Undo", disabled: true },
    { label: "Cut", disabled: true, shortcut: "Ctrl+X" },
    { label: "Copy", disabled: true, shortcut: "Ctrl+C" },
    { label: "Paste", disabled: true, shortcut: "Ctrl+V" },
    { label: "Select All", shortcut: "Ctrl+A" },
  ],
  view: [
    { label: "Status Bar" },
    { label: "Large Icons" },
    { label: "Small Icons" },
    { label: "List" },
    { label: "Details", disabled: true },
    {
      label: "Arrange Icons",
      items: [
        { label: "by Name" },
        { label: "by Type" },
        { label: "by Size" },
        { label: "by Date" },
      ],
    },
    { label: "Line Up Icons", disabled: true },
    { label: "Refresh", shortcut: "F5" },
  ],
  help: [
    { label: "Help Topics", disabled: true },
    { label: "About OpceanAI" },
  ],
};

export const vscodeNavigationMenuItems = {
  file: [
    { label: "New Text File", shortcut: "Ctrl+N" },
    { label: "Open File...", shortcut: "Ctrl+O" },
    { label: "Save", shortcut: "Ctrl+S" },
    { label: "Save As...", shortcut: "Ctrl+Shift+S" },
    { label: "Close Editor", shortcut: "Ctrl+W" },
  ],
  edit: [
    { label: "Undo", shortcut: "Ctrl+Z" },
    { label: "Redo", shortcut: "Ctrl+Y" },
    { label: "Cut", shortcut: "Ctrl+X" },
    { label: "Copy", shortcut: "Ctrl+C" },
    { label: "Paste", shortcut: "Ctrl+V" },
    { label: "Find", shortcut: "Ctrl+F" },
    { label: "Replace", shortcut: "Ctrl+H" },
  ],
  view: [
    { label: "Command Palette...", shortcut: "Ctrl+Shift+P" },
    { label: "Explorer", shortcut: "Ctrl+Shift+E" },
    { label: "Search", shortcut: "Ctrl+Shift+F" },
    { label: "Source Control", shortcut: "Ctrl+Shift+G" },
    { label: "Extensions", shortcut: "Ctrl+Shift+X" },
  ],
  help: [
    { label: "Welcome" },
    { label: "Documentation" },
    { label: "About OpceanAI" },
  ],
};

export const allMobileApps = [
  { label: "Notepad", iconImage: "/icons/notepad-2.png" },
  { label: "Documents", iconImage: "/folder.png" },
  { label: "Files", iconImage: "/file.png" },
  { label: "Internet", iconImage: "/icons/internet-explorer.png" },
  { label: "Gallery", iconImage: "/icons/paint.png" },
  { label: "Clock", iconImage: "/icons/date-time.png" },
  { label: "Calculator", iconImage: "/calculator.png" },
  { label: "Preferences", iconImage: "/icons/control-panel.png" },
  { label: "My Computer", iconImage: "/computer-explorer.png" },
  { label: "Recycle Bin", iconImage: "/recycle-bin.png" },
  { label: "Media Player", iconImage: "/icons/winamp.png" },
  { label: "Mail", iconImage: "/icons/modem.png" },
];
